import '@external/button/style/css'
import '@external/form/style/css'
import '@external/form-item/style/css'
import '@external/row/style/css'
import '@external/col/style/css'
import '@external/input/style/css'
import '@external/input-number/style/css'
import '@external/select/style/css'
import '@external/option/style/css'
import '@external/radio-group/style/css'
import '@external/checkbox-group/style/css'
import '@external/switch/style/css'
import '@external/cascader/style/css'
import '@external/date-picker/style/css'

import '@bole-component/theme/bo-filter.css'
import '@bole-component/theme/bo-form.css'
