import '@external/collapse-transition/style/css'
import '@external/tooltip/style/css'
import '@external/button/style/css'
import '@external/dropdown/style/css'
import '@external/popover/style/css'
import '@external/icon/style/css'
import '@external/tree/style/css'
import '@external/config-provider/style/css'

import '@bole-component/theme/bo-layout.css'
